apiVersion: v1
kind: Service
metadata:
  name: my-headless-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 39092
      targetPort: 39092
---
apiVersion: v1
kind: Endpoints
metadata:
  name: my-headless-service
subsets:
  - addresses:
      - ip: 10.1.0.8
    ports:
      - port: 39092
