apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: firasfrigui/challenge24_app
          env:
            - name: REACT_APP_BACK_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: BACKEND_URL
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    app: front
